site_name: "Module tp-experimentateur"
site_author: "AGBA Pascal Sébastien"
copyright: "2015-2022, AGBA Pascal Sébastien, Univ. Lille"
theme:
  name: "material"
  logo: ulille.png
  palette:
    primary: purple

nav:
  - Rendu: index.md
  - Experience documentation: experience.md
  - Marker documentation: marker.md
  - Sorting documentation: sorting.md
  
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        rendering:
          show_source: yes
        setup_commands:
          - import sys
          - sys.path.append('src/')
markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://www.fil.univ-lille.fr/~salson/portail/mathjax_conf.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
